version: '3'

services:
  mysql-docker-container1:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=restexample
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=password
    volumes:
      - /data/mysql
  spring-boot-jpa-app:
    image: rest-example-docker
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container1
    ports:
      - 8087:8080
    volumes:
      - /data/rest-example-docker